version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: league/flysystem
    versions:
    - 2.0.2
    - 2.0.3
    - 2.0.4
